### ISSUE TITLE
Replacing testify/assert.Equal

### ISSUE THREAD

**Issue by alecthomas** [gotestyourself/gotestyourself#73]
I have a [test in Participle](https://github.com/alecthomas/participle/blob/master/struct_test.go#L56) that compares two slices of `reflect.StructField`s. This works under testify with:

```go
assert.Equal(t, []reflect.StructField{f0, f0, f1}, f)
```

But does not work with gotestyourself with:

```go
assert.DeepEqual(t, []reflect.StructField{f0, f0, f1}, f, cmp.AllowUnexported(reflect.StructField{}))
```

Fails with:

```
	struct_test.go:57: assertion failed: cannot handle unexported field: {[]reflect.StructField}[0].Type.size
		consider using AllowUnexported or cmpopts.IgnoreUnexported
```

IgnoreUnexported reports the same error.

I believe the problem is that `StructField.Type` is an interface pointing at a concrete type that I don't have access to, so I can't allow access to it.

A solution is to modify my test to compare two slices of some other representation, but that kind of defeats the purpose of using a helper library.

Is there another solution?

Also, I don't quite understand what the advantage of go-cmp's strictness in this situation gives me as a user. It seems less useful and more verbose.

**Comment by alecthomas** [comment]
I also tried replacing the two slices with slices of `[]string{}` and using `assert.Equal(t, []string{f0, f0, f1}, f)` resulted in:

```
panic: runtime error: comparing uncomparable type []string [recovered]
	panic: runtime error: comparing uncomparable type []string
```

This makes sense as it uses `==` under the hood. `DeepEqual` worked.

What's the advantage (for a user) of having `Equal()` use `==` vs. deep equality checks?

**Comment by dnephin** [comment]
>  cannot handle unexported field: {[]reflect.StructField}[0].Type.size

Ah , yes that is an interesting case that I haven't hit yet. It would need to either allow or ignore unexported on the `reflect.Type` type, but that is an interface, and the implementations are unexported. Since there's no way to allow or ignore the type I think the best option is to provide a custom equality function for `reflect.Type`. I believe something like the diff below would be correct. The docs for `PkgPath` say "the import path uniquely identifies the package".

```diff
diff --git a/struct_test.go b/struct_test.go
index d01f84c..ecb5c11 100644
--- a/struct_test.go
+++ b/struct_test.go
@@ -5,7 +5,8 @@ import (
 	"testing"
 	"text/scanner"
 
-	"github.com/stretchr/testify/assert"
+	"github.com/gotestyourself/gotestyourself/assert"
+	"github.com/google/go-cmp/cmp"
 
 	"github.com/alecthomas/participle/lexer"
 )
@@ -53,5 +54,9 @@ func TestStructLexer(t *testing.T) {
 	assert.Equal(t, `a|b`, s)
 	f0 := gt.Field(0)
 	f1 := gt.Field(1)
-	assert.Equal(t, []reflect.StructField{f0, f0, f1}, f)
+	assert.DeepEqual(t, []reflect.StructField{f0, f0, f1}, f, cmpStructField)
 }
+
+var cmpStructField = cmp.Comparer(func(x, y reflect.Type) bool {
+	return x.PkgPath() == y.PkgPath() && x.Name() == y.Name()
+})
```

> I don't quite understand what the advantage of go-cmp's strictness in this situation gives me as a user. It seems less useful and more verbose.

I believe the reason this strictness is necessary is because it's not possible to tell if unexported fields are relevant to equality or not. One example of this is serializing/deserializing a `time.Time`. There are private fields in the struct which are not serialized, so comparing a value for `time.Time` after serialize/deserialize actually gives you "not equal", even though they represent the same value. I've hit this case a few times (where unexported fields cause `reflect.DeepEqual` to report not equal, even though I consider the objects to be equal).

So to remove that problem `go-cmp` gives you the flexibility to say when the fields are relevant or not.

**Comment by dnephin** [comment]
> What's the advantage (for a user) of having Equal() use == vs. deep equality checks?

My rational for this is:

There are cases when `DeepEqual` and `Equal` do not report the same result. The case I'm most familiar with is comparing pointers. Two pointers are equal if they point at the same address. Two pointers are `DeepEqual` if the values they reference are deep equal (they don't have to use the same address). There are times when you may want to check that a reference has changed to a copy of an object with the same value. You can't do that with `DeepEqual`.

Golang has specific definitions for `Equal` (`==`) and `DeepEqual` (`reflect.DeepEqual`). So using `DeepEqual` as `Equal` may confuse someone who is familiar with go, but not familiar with assertion libraries. This is feedback I received from a colleague during development. I believe I read somewhere that the name of the `go-cmp` package was changed from `eq` for the same reason (but I can't find that reference at the moment).
